In [3]:
import numpy as np
import jittor as jt
from jittor.utils.pytorch_converter import convert

In [ ]:
pytorch_code="""


"""


In [5]:
import jittor as jt
a = jt.Var(1)

In [37]:
# from jittor import nn
from jittor import models
import torch.nn as nn

class VGG19(nn.Module):
    def __init__(self, requires_grad=False):
        super().__init__()
        self.m1 = nn.Linear(12, 16 * 1 )
        exec('self.m%d = nn.Linear(2, 16 * 1 )' % 2)

    def execute(self, X):
        print(self.m1)
        print(self.m2)
        return X
b = 5
exec('a=b+1')
print(a)
m = VGG19()

# getattr(m, 'm2', None)
print(m)
m.m2 = None
m

6
VGG19(
  (m1): Linear(in_features=12, out_features=16, bias=True)
  (m2): Linear(in_features=2, out_features=16, bias=True)
)


VGG19(
  (m1): Linear(in_features=12, out_features=16, bias=True)
  (m2): None
)

In [62]:
import torch
input_label = torch.FloatTensor(1,3,2,2).zero_()
label_map = torch.tensor([0,0,1,2]).reshape(1,1,2,2).repeat(1,3,1,1)
label_map = label_map.type(torch.int64)
input_label.scatter_(1, label_map, 1.0)

# import jittor as jt
# input_label = jt.zeros((1,3,2,2),dtype='float32')
# label_map = jt.Var([0,0,1,2]).reshape(1,1,2,2).repeat(1,3,1,1)
# input_label.scatter_(1, label_map, jt.array(1.0))


tensor([[[[1., 1.],
          [0., 0.]],

         [[0., 0.],
          [1., 0.]],

         [[0., 0.],
          [0., 1.]]]])

In [116]:
from jittor import nn
import numpy as np
class Encoder(nn.Module):
    """ Same architecture as the image discriminator """
    def __init__(self):
        super().__init__()
        kw = 3
        pw = int(np.ceil((kw - 1.0) / 2))
        ndf = 12
        norm_layer = nn.Identity()
        self.layer1 = norm_layer(nn.Conv2d(3, ndf, kw, stride=2, padding=pw))
        self.layer2 = norm_layer(nn.Conv2d(ndf * 1, ndf * 2, kw, stride=2, padding=pw))
        self.layer3 = norm_layer(nn.Conv2d(ndf * 2, ndf * 4, kw, stride=2, padding=pw))
        self.layer4 = norm_layer(nn.Conv2d(ndf * 4, 3, kw, stride=2, padding=pw))
      
        self.actvn = nn.LeakyReLU(0.2)


    def execute(self, x):
        x = self.layer1(x)
        x = self.layer2(self.actvn(x))
        x = self.layer3(self.actvn(x))
        x = self.layer4(self.actvn(x))
        x = self.actvn(x)

        return x
def downsample(input):
    return nn.AvgPool2d(kernel_size=3,
                            stride=2, padding=1,
                            count_include_pad=False)(input)

x = jt.ones([40,32,48,64,],dtype='float32')
# encoder = Encoder()
# encoder(x)
downsample(x)

jt.Var([[[[0.44444445 0.6666667  0.6666667  ... 0.6666667  0.6666667
    0.6666667 ]
   [0.6666667  1.         1.         ... 1.         1.
    1.        ]
   [0.6666667  1.         1.         ... 1.         1.
    1.        ]
   ...
   [0.6666667  1.         1.         ... 1.         1.
    1.        ]
   [0.6666667  1.         1.         ... 1.         1.
    1.        ]
   [0.6666667  1.         1.         ... 1.         1.
    1.        ]]

  [[0.44444445 0.6666667  0.6666667  ... 0.6666667  0.6666667
    0.6666667 ]
   [0.6666667  1.         1.         ... 1.         1.
    1.        ]
   [0.6666667  1.         1.         ... 1.         1.
    1.        ]
   ...
   [0.6666667  1.         1.         ... 1.         1.
    1.        ]
   [0.6666667  1.         1.         ... 1.         1.
    1.        ]
   [0.6666667  1.         1.         ... 1.         1.
    1.        ]]

  [[0.44444445 0.6666667  0.6666667  ... 0.6666667  0.6666667
    0.6666667 ]
   [0.6666667  1.         1.   

In [149]:
jt.flags.use_cuda = 1
x = jt.ones([40,3,48,64,],dtype='float32')
# input_label = torch.FloatTensor(1).fill_(0)
# input_label
encoder = Encoder()
print(x.requires_grad)
x = x.detach()

with jt.no_grad():
    x = encoder(x )
    print(x.requires_grad)

    with jt.enable_grad():
        x = x.detach()
        print(x.requires_grad)
x

[i 0617 22:19:21.413669 92 cuda_flags.cc:32] CUDA enabled.


True
False
True


jt.Var([[[[ 0.02129825 -0.0038312  -0.0038312  -0.0038312 ]
   [ 0.02224597  0.01163984  0.01163984  0.01163984]
   [ 0.02224597  0.01163984  0.01163984  0.01163984]]

  [[-0.00520608 -0.00622648 -0.00622648 -0.00622648]
   [-0.00379688 -0.00945618 -0.00945618 -0.00945618]
   [-0.00379688 -0.00945618 -0.00945618 -0.00945618]]

  [[ 0.05037353  0.0503072   0.0503072   0.0503072 ]
   [ 0.0467836   0.04808769  0.04808769  0.04808769]
   [ 0.0467836   0.04808769  0.04808769  0.04808769]]]


 [[[ 0.02129825 -0.0038312  -0.0038312  -0.0038312 ]
   [ 0.02224597  0.01163984  0.01163984  0.01163984]
   [ 0.02224597  0.01163984  0.01163984  0.01163984]]

  [[-0.00520608 -0.00622648 -0.00622648 -0.00622648]
   [-0.00379688 -0.00945618 -0.00945618 -0.00945618]
   [-0.00379688 -0.00945618 -0.00945618 -0.00945618]]

  [[ 0.05037353  0.0503072   0.0503072   0.0503072 ]
   [ 0.0467836   0.04808769  0.04808769  0.04808769]
   [ 0.0467836   0.04808769  0.04808769  0.04808769]]]


 [[[ 0.02129825 -0.0038

In [134]:

Tensor = torch.FloatTensor
def get_zero_tensor(input):
        zero_tensor = Tensor(1).fill_(0)
        zero_tensor.requires_grad_(False)
        return zero_tensor.expand_as(input)


inp = torch.randn(2,3,4,4)
inp.shape
inp2 = jt.randn(2,3,4,4)
inp2.shape
torch.min(-inp-1,get_zero_tensor(inp))



tensor([[[[-0.6575, -1.2519, -1.5749, -1.3080],
          [-0.5012, -0.1550, -0.7069, -1.0683],
          [-0.7066, -1.0580, -0.0431, -1.4339],
          [-0.6376,  0.0000, -1.2631, -1.6846]],

         [[-0.8129,  0.0000, -0.2960, -1.2395],
          [-1.6352, -0.4712,  0.0000, -1.4125],
          [ 0.0000, -1.8431, -2.6343, -1.7285],
          [-1.7550, -1.7589, -0.4913, -2.8552]],

         [[-2.5312,  0.0000,  0.0000, -0.9449],
          [ 0.0000, -1.6963, -0.3919,  0.0000],
          [-0.8014, -0.4813, -2.5086, -1.7754],
          [ 0.0000, -1.2154, -0.6087, -2.1910]]],


        [[[-0.1517, -1.0859, -0.3034, -0.8581],
          [-1.8500,  0.0000, -1.7606,  0.0000],
          [-1.0182,  0.0000, -0.1587,  0.0000],
          [ 0.0000, -0.5965, -1.3591, -2.5474]],

         [[-1.1704, -2.7145, -1.6092, -0.6868],
          [ 0.0000, -0.1040, -0.7400, -2.3667],
          [-0.6486,  0.0000,  0.0000,  0.0000],
          [ 0.0000, -1.6745, -1.8859, -1.4478]],

         [[-0.3715, -0.4300,

In [147]:
Tensor = jt.float16
def get_zero_tensor(input):
        zero_tensor = Tensor(0)
        zero_tensor.stop_grad()
        return zero_tensor.expand_as(input)
get_zero_tensor(inp2)
a = jt.minimum(inp2,get_zero_tensor(inp2))
a.mean().get_device() 

AttributeError: 'jittor_core.Var' object has no attribute 'get_device'

In [39]:

import jittor as jt
from jittor import init
from jittor import nn
import numpy as np
from models.networks.base_network import BaseNetwork
from models.networks.normalization import get_nonspade_norm_layer
jt.flags.use_cuda = 1
# jt.flags.auto_mixed_precision_level = 5


class ConvEncoder(BaseNetwork):
    """ Same architecture as the image discriminator """

    def __init__(self):
        super().__init__()

        kw = 3
        pw = int(np.ceil((kw - 1.0) / 2))
        ndf = 64
        norm_layer = nn.Identity()
        self.layer1 = norm_layer(nn.Conv2d(29, ndf, kw, stride=2, padding=pw))
        self.layer2 = norm_layer(nn.Conv2d(ndf * 1, ndf * 2, kw, stride=2, padding=pw))
        self.layer3 = norm_layer(nn.Conv2d(ndf * 2, ndf * 4, kw, stride=2, padding=pw))
        self.layer4 = norm_layer(nn.Conv2d(ndf * 4, ndf * 8, kw, stride=2, padding=pw))
        self.layer5 = norm_layer(nn.Conv2d(ndf * 8, ndf * 8, kw, stride=2, padding=pw))
        self.layer6 = norm_layer(nn.Conv2d(ndf * 8, ndf * 8, kw, stride=2, padding=pw))

            # re-load layer1 and layer6
        self.actvn = nn.LeakyReLU(0.2, False)
   

    def execute(self, x):
        x = self.layer1(x)
        x = self.layer2(nn.leaky_relu(x,0.2))
        x = self.layer3(nn.leaky_relu(x,0.2))
        x = self.layer4(nn.leaky_relu(x,0.2))
        x = self.layer5(nn.leaky_relu(x,0.2))
        x = self.layer6(nn.leaky_relu(x,0.2))
        x = nn.leaky_relu(x,0.2)

        return x
        

x = jt.ones((20,29,384,512))
x = jt.float16(x)
encd = ConvEncoder()
with jt.flag_scope(auto_mixed_precision_level=0):
    y = encd(x)
# y.shape, type(y), y.dtype,y
for m in encd.children():
    print(m.weight.dtype)

[i 0618 14:28:25.505722 24 cuda_flags.cc:32] CUDA enabled.


float16
float16
float16
float16
float16
float16


AttributeError: 'leaky_relu' object has no attribute 'weight'

In [11]:
class ConvEncoder_more(BaseNetwork):
    """ Same architecture as the image discriminator """

    def __init__(self):
        super().__init__()

        kw = 3
        pw = int(np.ceil((kw - 1.0) / 2))
        ndf = 64
        norm_layer = nn.Identity()
        self.layer1 = norm_layer(nn.Conv2d(3, ndf, kw, stride=2, padding=pw))
        self.layer2 = norm_layer(nn.Conv2d(ndf * 1, ndf * 2, kw, stride=2, padding=pw))
        self.layer3 = norm_layer(nn.Conv2d(ndf * 2, ndf * 4, kw, stride=2, padding=pw))
        self.layer4 = norm_layer(nn.Conv2d(ndf * 4, ndf * 8, kw, stride=2, padding=pw))
        self.layer5 = norm_layer(nn.Conv2d(ndf * 8, ndf * 8, kw, stride=2, padding=pw))
        self.layer6 = norm_layer(nn.Conv2d(ndf * 8, ndf * 8, kw, stride=2, padding=pw))
        self.layer7 = norm_layer(nn.Conv2d(ndf * 8, ndf * 8, kw, stride=2, padding=pw))

            # re-load layer1 and layer6
        self.layer1 = norm_layer(nn.Conv2d(29, ndf, kw, stride=2, padding=pw))
        self.layer6 = norm_layer(nn.Conv2d(ndf * 8, ndf * 16, kw, stride=2, padding=pw))

        self.so = s0 = 4
        self.fc_mu = nn.Linear(ndf * 8 * s0 * s0, 256)
        self.fc_var = nn.Linear(ndf * 8 * s0 * s0, 256)

        self.actvn = nn.LeakyReLU(0.2, False)
   

    def execute(self, x):
        x = self.layer1(x)
        x = self.layer2(nn.leaky_relu(x,0.2))
        x = self.layer3(nn.leaky_relu(x,0.2))
        x = self.layer4(nn.leaky_relu(x,0.2))
        x = self.layer5(nn.leaky_relu(x,0.2))
        x = self.layer6(nn.leaky_relu(x,0.2))
        x = nn.leaky_relu(x,0.2)

        return x
encd2 = ConvEncoder_more()
encd2.load_state_dict(encd.state_dict())
encd2(x)

jt.Var([[[[-0.00203571 -0.00259454 -0.00259454 ... -0.00259454 -0.00259454
    -0.00259454]
   [-0.00163781 -0.00111778 -0.00111778 ... -0.00111778 -0.00111778
    -0.00111778]
   [-0.00163781 -0.00111778 -0.00111778 ... -0.00111778 -0.00111778
    -0.00111778]
   [-0.00163781 -0.00111778 -0.00111778 ... -0.00111778 -0.00111778
    -0.00111778]
   [-0.00163781 -0.00111778 -0.00111778 ... -0.00111778 -0.00111778
    -0.00111778]
   [-0.00163781 -0.00111778 -0.00111778 ... -0.00111778 -0.00111778
    -0.00111778]]

  [[-0.00142581 -0.00171824 -0.00171824 ... -0.00171824 -0.00171824
    -0.00171824]
   [-0.001165   -0.00018073 -0.00018073 ... -0.00018073 -0.00018073
    -0.00018073]
   [-0.001165   -0.00018073 -0.00018073 ... -0.00018073 -0.00018073
    -0.00018073]
   [-0.001165   -0.00018073 -0.00018073 ... -0.00018073 -0.00018073
    -0.00018073]
   [-0.001165   -0.00018073 -0.00018073 ... -0.00018073 -0.00018073
    -0.00018073]
   [-0.001165   -0.00018073 -0.00018073 ... -0.00018073 

In [1]:

jt.flags.auto_mixed_precision_level = 5
x = jt.float32(x)
x

NameError: name 'jt' is not defined